license="${mod_license}"
modLoader="javafml"
loaderVersion="${loader_version_range}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/talhanation/workers/main/update.json"
displayURL="https://modrinth.com/mod/villager-workers"
logoFile="logo.png"
credits="talhanation"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="mixins.workers.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="recruits"
type="required"
versionRange="${recruits_version_range}"
ordering="AFTER"
side="BOTH"
